// prisma/seed.ts
import { PrismaClient } from "@prisma/client";
const prisma = new PrismaClient();

async function main() {
  await prisma.evento.createMany({
    data: [
      {
        nombre: "Festival Rock Miraflores",
        descripcion: "Bandas locales y food trucks frente al malecón.",
        direccion: "Parque Kennedy",
        distrito: "MIRAFLORES",
        fecha_inicio: new Date("2025-11-20T18:00:00"),
        fecha_fin: new Date("2025-11-20T23:00:00"),
        hora_inicio: 18,
        duracion: 300,
        aforo: 1000,
        estado: "PUBLICADO",
        tipoEvento: "CONCIERTO",
        subtipo: "GENERAL"
      },
      {
        nombre: "Feria Gastronómica Surco",
        descripcion: "Cocina peruana, postres y música en vivo.",
        direccion: "Plaza Mayor de Surco",
        distrito: "SANTIAGO_DE_SURCO",
        fecha_inicio: new Date("2025-11-25T12:00:00"),
        fecha_fin: new Date("2025-11-25T20:00:00"),
        hora_inicio: 12,
        duracion: 480,
        aforo: 2000,
        estado: "PUBLICADO",
        tipoEvento: "TRENDING",
        subtipo: "GENERAL"
      },
      {
        nombre: "Concierto Electrónico Barranco",
        descripcion: "DJ sets y visuales en club subterráneo.",
        direccion: "Avenida San Martín",
        distrito: "BARRANCO",
        fecha_inicio: new Date("2025-11-22T22:00:00"),
        fecha_fin: new Date("2025-11-23T03:00:00"),
        hora_inicio: 22,
        duracion: 300,
        aforo: 800,
        estado: "PUBLICADO",
        tipoEvento: "CONCIERTO",
        subtipo: "MAS18"
      },
      {
        nombre: "Carrera 10K Nocturna Lima",
        descripcion: "Competencia urbana con hidratación y música en vivo.",
        direccion: "Circuito Mágico del Agua",
        distrito: "LIMA",
        fecha_inicio: new Date("2025-12-02T19:00:00"),
        fecha_fin: new Date("2025-12-02T22:00:00"),
        hora_inicio: 19,
        duracion: 180,
        aforo: 5000,
        estado: "PUBLICADO",
        tipoEvento: "DEPORTE",
        subtipo: "GENERAL"
      },
      {
        nombre: "Obra Comedia Impro San Borja",
        descripcion: "Actuaciones espontáneas con participación del público.",
        direccion: "Teatro Julio Ramón Ribeyro",
        distrito: "SAN_BORJA",
        fecha_inicio: new Date("2025-11-28T20:00:00"),
        fecha_fin: new Date("2025-11-28T22:30:00"),
        hora_inicio: 20,
        duracion: 150,
        aforo: 400,
        estado: "PUBLICADO",
        tipoEvento: "TEATRO",
        subtipo: "GENERAL"
      },
      {
        nombre: "Expo Emprendedores Miraflores",
        descripcion: "Muestra de negocios locales y charlas inspiradoras.",
        direccion: "Parque del Amor",
        distrito: "MIRAFLORES",
        fecha_inicio: new Date("2025-11-27T10:00:00"),
        fecha_fin: new Date("2025-11-27T18:00:00"),
        hora_inicio: 10,
        duracion: 480,
        aforo: 1000,
        estado: "PUBLICADO",
        tipoEvento: "TRENDING",
        subtipo: "GENERAL"
      },
      {
        nombre: "Torneo Relámpago Fútbol Chorrillos",
        descripcion: "Competencia deportiva entre barrios con premiación.",
        direccion: "Estadio Municipal de Chorrillos",
        distrito: "CHORRILLOS",
        fecha_inicio: new Date("2025-12-03T09:00:00"),
        fecha_fin: new Date("2025-12-03T15:00:00"),
        hora_inicio: 9,
        duracion: 360,
        aforo: 800,
        estado: "PUBLICADO",
        tipoEvento: "DEPORTE",
        subtipo: "GENERAL"
      },
      {
        nombre: "Feria Cultural Barranco",
        descripcion: "Arte, gastronomía y presentaciones musicales al aire libre.",
        direccion: "Parque Municipal de Barranco",
        distrito: "BARRANCO",
        fecha_inicio: new Date("2025-12-01T11:00:00"),
        fecha_fin: new Date("2025-12-01T20:00:00"),
        hora_inicio: 11,
        duracion: 540,
        aforo: 1500,
        estado: "PUBLICADO",
        tipoEvento: "TRENDING",
        subtipo: "GENERAL"
      },
      {
        nombre: "Drama Urbano San Isidro",
        descripcion: "Obra teatral moderna con enfoque social.",
        direccion: "Teatro del Centro Empresarial",
        distrito: "SAN_ISIDRO",
        fecha_inicio: new Date("2025-12-05T19:30:00"),
        fecha_fin: new Date("2025-12-05T22:00:00"),
        hora_inicio: 19,
        duracion: 150,
        aforo: 350,
        estado: "PUBLICADO",
        tipoEvento: "TEATRO",
        subtipo: "GENERAL"
      },
      {
        nombre: "Festival Techno Subterráneo Surquillo",
        descripcion: "Fiesta electrónica con DJs internacionales y luces LED.",
        direccion: "Club Nocturno Nexus",
        distrito: "SURQUILLO",
        fecha_inicio: new Date("2025-12-07T22:00:00"),
        fecha_fin: new Date("2025-12-08T03:00:00"),
        hora_inicio: 22,
        duracion: 300,
        aforo: 1000,
        estado: "PUBLICADO",
        tipoEvento: "CONCIERTO",
        subtipo: "MAS18"
      },
      {
        nombre: "Carrera Solidaria San Miguel",
        descripcion: "Evento deportivo para recaudar fondos benéficos.",
        direccion: "Parque Media Luna",
        distrito: "SAN_MIGUEL",
        fecha_inicio: new Date("2025-12-10T08:00:00"),
        fecha_fin: new Date("2025-12-10T12:00:00"),
        hora_inicio: 8,
        duracion: 240,
        aforo: 3000,
        estado: "PUBLICADO",
        tipoEvento: "DEPORTE",
        subtipo: "GENERAL"
      },
      {
        nombre: "Festival Indie Surco",
        descripcion: "Bandas emergentes presentan sus mejores temas en vivo.",
        direccion: "Anfiteatro Surco",
        distrito: "SANTIAGO_DE_SURCO",
        fecha_inicio: new Date("2025-12-14T18:00:00"),
        fecha_fin: new Date("2025-12-14T23:00:00"),
        hora_inicio: 18,
        duracion: 300,
        aforo: 1200,
        estado: "PUBLICADO",
        tipoEvento: "CONCIERTO",
        subtipo: "GENERAL"
      },
      {
        nombre: "Obra de Impro Miraflores",
        descripcion: "Actores improvisan historias basadas en temas del público.",
        direccion: "Teatro Marsano",
        distrito: "MIRAFLORES",
        fecha_inicio: new Date("2025-12-12T19:00:00"),
        fecha_fin: new Date("2025-12-12T21:00:00"),
        hora_inicio: 19,
        duracion: 120,
        aforo: 250,
        estado: "PUBLICADO",
        tipoEvento: "TEATRO",
        subtipo: "GENERAL"
      },
      {
        nombre: "Festival Gastronómico Magdalena",
        descripcion: "Sabores del Perú con presentaciones musicales y sorteos.",
        direccion: "Parque Túpac Amaru",
        distrito: "MAGDALENA_DEL_MAR",
        fecha_inicio: new Date("2025-12-09T10:00:00"),
        fecha_fin: new Date("2025-12-09T20:00:00"),
        hora_inicio: 10,
        duracion: 600,
        aforo: 2000,
        estado: "PUBLICADO",
        tipoEvento: "TRENDING",
        subtipo: "GENERAL"
      },
      {
        nombre: "Concierto Acústico Surco",
        descripcion: "Noche íntima con artistas de música folk y baladas.",
        direccion: "Auditorio Surco Viejo",
        distrito: "SANTIAGO_DE_SURCO",
        fecha_inicio: new Date("2025-12-15T20:00:00"),
        fecha_fin: new Date("2025-12-15T22:30:00"),
        hora_inicio: 20,
        duracion: 150,
        aforo: 500,
        estado: "PUBLICADO",
        tipoEvento: "CONCIERTO",
        subtipo: "GENERAL"
      },
      {
        nombre: "Torneo de Surf Punta Hermosa",
        descripcion: "Competencia de surfistas profesionales nacionales.",
        direccion: "Playa Blanca",
        distrito: "PUNTA_HERMOSA",
        fecha_inicio: new Date("2025-12-17T09:00:00"),
        fecha_fin: new Date("2025-12-17T14:00:00"),
        hora_inicio: 9,
        duracion: 300,
        aforo: 1500,
        estado: "PUBLICADO",
        tipoEvento: "DEPORTE",
        subtipo: "GENERAL"
      },
      {
        nombre: "Rave Electrónica Lima",
        descripcion: "Evento techno con visuales inmersivos y DJs reconocidos.",
        direccion: "Centro de Convenciones de Lima",
        distrito: "LIMA",
        fecha_inicio: new Date("2025-12-20T23:00:00"),
        fecha_fin: new Date("2025-12-21T05:00:00"),
        hora_inicio: 23,
        duracion: 360,
        aforo: 2500,
        estado: "PUBLICADO",
        tipoEvento: "CONCIERTO",
        subtipo: "MAS18"
      },
      {
        nombre: "Microteatro Nocturno San Borja",
        descripcion: "Obras breves de distintos géneros en una sola noche.",
        direccion: "Centro Cultural San Borja",
        distrito: "SAN_BORJA",
        fecha_inicio: new Date("2025-12-22T20:00:00"),
        fecha_fin: new Date("2025-12-22T22:00:00"),
        hora_inicio: 20,
        duracion: 120,
        aforo: 300,
        estado: "PUBLICADO",
        tipoEvento: "TEATRO",
        subtipo: "GENERAL"
      },
      {
        nombre: "Expo Startups Lima",
        descripcion: "Evento tecnológico con charlas, networking y demos de apps.",
        direccion: "Centro de Innovación PUCP",
        distrito: "LIMA",
        fecha_inicio: new Date("2025-12-18T09:00:00"),
        fecha_fin: new Date("2025-12-18T17:00:00"),
        hora_inicio: 9,
        duracion: 480,
        aforo: 1000,
        estado: "PUBLICADO",
        tipoEvento: "TRENDING",
        subtipo: "GENERAL"
      },
      {
        nombre: "Festival de Teatro Juvenil Comas",
        descripcion: "Presentaciones de colegios con temáticas sociales y culturales.",
        direccion: "Auditorio Comas Joven",
        distrito: "COMAS",
        fecha_inicio: new Date("2025-12-19T16:00:00"),
        fecha_fin: new Date("2025-12-19T20:00:00"),
        hora_inicio: 16,
        duracion: 240,
        aforo: 600,
        estado: "PUBLICADO",
        tipoEvento: "TEATRO",
        subtipo: "INFANTIL"
      }
    ],
    skipDuplicates: true
  });

  console.log("✅ Seed con 20 eventos insertado correctamente.");
}

main().finally(() => prisma.$disconnect());
